name: CodeAuditor Feedback Loop Workflow
description: This is an action that creates new issues if there is an increase in the number of errors found from CodeAuditor scan
author: Tom Bui
branding:
  icon: 'paperclip'
  color: 'red'

inputs:
  GitHub_Token:
    description: 'Your GitHub Token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Test gh cli
      shell: bash
      env:
        GH_TOKEN: ${{inputs.GitHub_Token}}
      run: |
        echo "Create issue for increased code warnings"
        gh issue \
          create --title "⚠️ CodeAuditor Alert - Increased number of HTML Warnings detected" \
          --body "
          ## New HTML Warnings detected
            
          - [ ] Please fix remaining HTML Warnings"
