name: CodeAuditor Feedback Loop Workflow
description: This is an action that creates new issues if there is an increase in the number of errors found from CodeAuditor scan
author: Tom Bui
runs:
  using: 'docker'
  image: 'Dockerfile'
