name: CodeAuditor Feedback Loop Workflow

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Your CodeAuditor token'
        required: true
      url:
        description: 'Your URL'
        required: true

# A workflow run is made up of one or more jobsjj that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: "SSW CodeAuditor - Check broken links and performance"
        continue-on-error: true
        run: |
          curl --request GET 'https://asia-east2-sswlinkauditor-c1131.cloudfunctions.net/api/comparescanlatestandsecond/${{github.event.inputs.token}}/${{github.event.inputs.url}}' -o content.json
      
      - name: output api content
        id: content
        run: echo "::set-output name=id::$(cat content.json)"
        
      - name: If number of Code Warnings increases
        if: "${{fromJson(steps.content.outputs.id).isHtmlWarningsUp}}"
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          echo "Create issue for increased code warnings"
          gh issue \
            create --title "⚠️ CodeAuditor Alert - Increased number of HTML Warnings detected" \
            --body "
            ## New HTML Warnings detected
            
            ⚠️ The number of HTML Warnings has gone up by **$((${{fromJson(steps.content.outputs.id).currHtmlWarnings}} - ${{fromJson(steps.content.outputs.id).prevHtmlWarnings}}))** from **${{fromJson(steps.content.outputs.id).prevHtmlWarnings}}** to **${{fromJson(steps.content.outputs.id).currHtmlWarnings}}**
            
            See [Latest Scan Details ](https://codeauditor.com/build/${{fromJson(steps.content.outputs.id).latestRunId}})
              
            - [ ] Please fix remaining HTML Warnings"
      
      - name: If number of Code Errors increases
        if: "${{fromJson(steps.content.outputs.id).isHtmlErrorsUp}}"
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          echo "Create issue for increased code errors"
          gh issue \
            create --title "❌ CodeAuditor Alert - Increased number of HTML Errors detected" \
            --body "
            ## New HTML Errors detected
            
            ❌ The number of HTML Errors has gone up by **$((${{fromJson(steps.content.outputs.id).currHtmlErrors}} - ${{fromJson(steps.content.outputs.id).prevHtmlErrors}}))** from **${{fromJson(steps.content.outputs.id).prevHtmlErrors}}** to **${{fromJson(steps.content.outputs.id).currHtmlErrors}}**
            
            See [Latest Scan Details ](https://codeauditor.com/build/${{fromJson(steps.content.outputs.id).latestRunId}})
              
            - [ ] Please fix remaining HTML Errors"

      - name: If number of Broken Links increases
        if: "${{fromJson(steps.content.outputs.id).isBrokenLinksUp}}"
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          echo "Create issue for increased broken links"
          gh issue \
            create --title "❗ CodeAuditor Alert - Increased number of Broken Links detected" \
            --body "
            ## New Broken Links detected
            
            ❗ The number of Broken Links has gone up by **$((${{fromJson(steps.content.outputs.id).currBrokenLinks}} - ${{fromJson(steps.content.outputs.id).prevBrokenLinks}}))** from **${{fromJson(steps.content.outputs.id).prevBrokenLinks}}** to **${{fromJson(steps.content.outputs.id).currBrokenLinks}}**
            
            See [Latest Scan Details ](https://codeauditor.com/build/${{fromJson(steps.content.outputs.id).latestRunId}})
              
            - [ ] Please fix remaining Broken Links"
            
