name: CodeAuditor test

on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobsjj that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: "SSW CodeAuditor - Check broken links and performance"
        continue-on-error: true
        run: |
          curl --request GET 'https://asia-east2-sswlinkauditor-c1131.cloudfunctions.net/api/comparescanlatestandsecond/3c34a549-dfb3-442c-b0e3-45942104a8bf/https%3A%2F%2Fwww.htmlhint.com%2F' -o content.json
      
      - name: read api content
        id: content
        run: echo "::set-output name=id::$(cat content.json)"

      - name: read content
        run: echo "${{fromJson(steps.content.outputs.id)}}"

      - name: If number of Code Warnings increases
        if: "${{fromJson(steps.content.outputs.id).isHtmlWarningsUp}}"
        run: echo "Create issue for increased code warnings"
      
      - name: If number of Code Errors increases
        if: "${{fromJson(steps.content.outputs.id).isHtmlErrorsUp}}"
        run: echo "Create issue for increased code errors"

      - name: If number of Broken Links increases
        if: "${{fromJson(steps.content.outputs.id).isBrokenLinksUp}}"
        run: echo "Create issue for increased broken links"
        
        # run: "docker run sswconsulting/codeauditor --token 3c34a549-dfb3-442c-b0e3-45942104a8bf --url htmlhint.com --private"
