name: CodeAuditor test

on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobsjj that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: "SSW CodeAuditor - Check broken links and performance"
        continue-on-error: true
        run: |
          curl --request GET 'https://asia-east2-sswlinkauditor-c1131.cloudfunctions.net/api/comparescanlatestandsecond/3c34a549-dfb3-442c-b0e3-45942104a8bf/https%3A%2F%2Fwww.htmlhint.com%2F' -o content.json
      
      - name: output api content
        id: content
        run: echo "::set-output name=id::$(cat content.json)"
        
      - name: If number of Code Warnings increases
        if: "${{fromJson(steps.content.outputs.id).isHtmlWarningsUp}}"
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          echo "Create issue for increased code warnings"
          gh issue \
            create --title "Increased number of HTML Warnings detected" \
            --body "The number of HTML Warnings has gone up from ${{fromJson(steps.content.outputs.id).prevHtmlWarnings}} to ${{fromJson(steps.content.outputs.id).currHtmlWarnings}}"
      
      - name: If number of Code Errors increases
        if: "${{fromJson(steps.content.outputs.id).isHtmlErrorsUp}}"
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          echo "Create issue for increased code errors"
          gh issue create --title "Increased number of HTML Errors detected" --body "Here are more details."

      - name: If number of Broken Links increases
        if: "${{fromJson(steps.content.outputs.id).isBrokenLinksUp}}"
        env:
          GH_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          echo "Create issue for increased broken links"
          gh issue create --title "Increased number of Broken Links detected" --body "Here are more details."
                  
        # run: "docker run sswconsulting/codeauditor --token 3c34a549-dfb3-442c-b0e3-45942104a8bf --url htmlhint.com --private"
