name: CodeAuditor test

on:
  push:
    branches: [main]

# A workflow run is made up of one or more jobsjj that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: "SSW CodeAuditor - Check broken links and performance"
        continue-on-error: true
        run: "docker run sswconsulting/codeauditor --url htmlhint.com --debug"
