name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Manually fail the workflow
        continue-on-error: true
        run: exit 1
      - name: "Send issue report if scan fails"
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: echo "Current time: $(date +'%Y-%m-%d %H:%M:%S')"
