name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Manually fail the workflow
        run: exit 1
      - name: Check exit code
        if: ${{ failure() }}
        run: |
          cat ${{ github.workspace }}/step4.log
          
