name: Test CodeAuditor Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: CodeAuditor Feedback Loop Workflow
        uses: tombui99/codeauditor-github-workflow@1.0.0
        with:
          # Your CodeAuditor token
          token: ${{ vars.CODEAUDITORTOKEN }}
          # Your Scan URL
          url: ${{ vars.SCANURL }}
          # Your GitHub Token
          GitHub_Token: ${{secrets.GH_TOKEN}}
