name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Manually fail the workflow
        run: exit 1
      - name: Check exit code
        if: ${{ failure() }}
        run: | 
          echo "Error occurred with exit code ${{ job.status }}"
          echo ${{ github.event.repository.updated_at}} | sed 's/:/./g'
