name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Manually fail the workflow
        run: |
          exit 1
      - name: Check exit code
        if: ${{ failure() }}
        run: |
          echo "$(date +"%Y-%m-%d %H:%M:%S")"
          curl \
            -X POST 'https://asia-east2-sswlinkauditor-c1131.cloudfunctions.net/api/createReportIssue' \
            -H 'Content-Type: application/json' \
            -d "{\"url\": \"${{ job.status }}\", \"dateReported\": \"$(date +"%Y-%m-%d %H:%M:%S")\", \"workflowId\": \"${{ github.run_id }}\", \"jobStatus\": \"${{ job.status }}\"}" \

