name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Manually fail the workflow
        run: exit 1
      - name: Check exit code
        if: ${{ failure() }}
        run: | 
          echo "Current date and time: $(date +"%H:%M:%S %d-%m-%Y")"
