name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Manually fail the workflow
        id: docker_run
        run: |
          echo "::set-output name=docker_output::$(docker run sswconsulting/codeauditor --url htmlhint.com)"
          continue-on-error: true
          exit 1
      - name: Check exit code
        if: ${{ failure() }}
        run: |
          echo "${{ steps.docker_run.outputs.docker_output }}"
