name: Test CodeAuditor Workflow 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tom - Test workflow
        uses: tombui99/codeauditor-github-workflow@1.0.0
        with:
          GitHub_Token: ${{ github.token }}
