name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Manually fail the workflow
        run: |
          docker run sswconsulting/codeauditor --url htmlhint.com > docker_step.log
          exit 1
      - name: Check exit code
        if: ${{ failure() }}
        run: |
          cat docker_step.log
          
