name: Test CodeAuditor Workflow

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Your CodeAuditor token'
        required: true
      url:
        description: 'Your URL'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CodeAuditor Feedback Loop Workflow
        uses: tombui99/codeauditor-github-workflow@v1.0.0
        with:
          # Your CodeAuditor token
          token: ${{github.event.inputs.token}}
          # Your URL
          url: ${{github.event.inputs.url}}
          # Your GitHub Token
          GitHub_Token: ${{secrets.GH_TOKEN}}