name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Manually fail the workflow
        run: |
          echo "Error occurred in step 4" > step4.log # Write error message to a file
          exit 1
      - name: Check exit code
        if: ${{ failure() }}
        run: |
          cat step4.log # Print contents of the log file
          
