name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Manually fail the workflow
        run: exit 1
      - name: Check exit code
        if: ${{ failure() }}
        run: | 
          echo "Current date and time: $(date +"%Y-%m-%d %H:%M:%S")"
          echo "Current date and time: ${{ github.event.repository.updated_at }}"
