name: CodeAuditor Feedback Loop Workflow

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Your CodeAuditor token'
        required: true
      url:
        description: 'Your URL'
        required: true

# A workflow run is made up of one or more jobsjj that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: "SSW CodeAuditor - Check broken links and performance"
        run: |
            curl \
                -X POST \
                -H "Accept: application/vnd.github.v3+json" \
                https://asia-east2-sswlinkauditor-c1131.cloudfunctions.net/api/comparescanlatestandsecond/${{inputs.token}} \
                -d '{"url": "${{inputs.url}}"}' \
                -o content.json  
      - name: output api content
        id: content
        run: echo "::set-output name=id::$(cat content.json)"
      - name: read out
        run: echo ${{ steps.content.outputs.id }}
      
        
